### ISSUE TITLE
Change charge rate to W instead of Wh

### ISSUE THREAD

**Issue by jinu-jacob** [FireCubeStudios/FluentFlyouts3#12]
Electrical energy is calculated in **kW h** (here **W h** or watt-hour). But when it comes to rate its different. Rate means per time. So, hour(time) in watthour gets cancelled and only watt(W) remains.

$rate = \frac{energy}{time} = \frac{W \cancel{h} }{ \cancel{h}} = W$

**Comment by FireCubeStudios** [comment]
I see. Ok this should be a simple fix. Thanks for posting the equation I completely forgot basic physics

**Comment by gaurav-iitb** [comment]
can you please assign this to me

**Comment by FireCubeStudios** [comment]
Fixed in #17

**Comment by jinu-jacob** [comment]
Bravo
