### ISSUE TITLE
Feature Request: Re-use existing taskbar icon

### ISSUE THREAD

**Issue by danchar4** [FireCubeStudios/FluentFlyouts3#15]
Instead of creating a second systray icon, re-use the original one or disable the original so there isn't a duplicate.

This is easier said than done...

**Comment by FireCubeStudios** [comment]
A second system tray icon isn't created. What are you referring to?

**Comment by danchar4** [comment]
Oh interesting - I wonder if if the double icon issue is related to the crashing issue #14. Anyway here is a screenshot:

 
![image](https://user-images.githubusercontent.com/13006912/194971688-55d51b99-e959-4ecd-af36-eabb835130b3.png)

**Comment by FireCubeStudios** [comment]
This isn't possible to replace windows 10 shell systray
