### ISSUE TITLE
Flyout Doesn't Respect My Taskbar Location

### ISSUE THREAD

**Issue by JayBigGuy10** [FireCubeStudios/FluentFlyouts3#16]
![image](https://user-images.githubusercontent.com/42988261/194980668-121c6ec1-824b-4ee8-95e5-0d3bc9c1706a.png)

Running On Windows10, surfacePro7

**Comment by FireCubeStudios** [comment]
Oop I forgot taskbar orientations exist in windows 10

**Comment by FireCubeStudios** [comment]
The next update will support dragging the flyout to a desired location. This has already been fixed in the github repo and a store release is coming

**Comment by FireCubeStudios** [comment]
Ok 3.1.9.0 adds support to drag the flyout to the top if you want so this is resolved
