### ISSUE TITLE
Accessibility: fix navigation between interactive elements via tab key

### ISSUE THREAD

**Issue by danchar4** [FireCubeStudios/FluentFlyouts3#20]
Severity: minor
Priority: low

Repro:
- open flyout
- hit tab key repeatedly

Expected:
- The system caret should alternate back and forth between the settings icon and the power slider when tab is pressed as these are the only interactive elements

Actual:
- The system caret seems to navigate to hidden or non-interactive elements in between settings and slider
- Caret doesn't cycle back to 1st element after reaching last - need to press shift-tab to go back.

**Comment by FireCubeStudios** [comment]
I believe this is now fixed thanks to your pr #24
