### ISSUE TITLE
WinUI 3: Icon not showing in titlebar

### ISSUE THREAD

**Issue by FireCubeStudios** [FireCubeStudios/FluentFlyouts3#3]
Since switch to packaging project there is no app icon in the titlebar of settings window. Easy fix simply update the link to the icon to use the FluentFlyouts3.Package rather than FluentFlyouts3.

**Comment by Rutuj-Runwal** [comment]
@FireCubeStudios I am interested in this project but I am new to WinUI3 can you provide some instructions on how to build/compile the project?
Will be glad to learn and help

**Comment by FireCubeStudios** [comment]
You will need to install these tools:https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=vs-2022-17-1-a%2Cvs-2022-17-1-b

After that simply running the FluentFlyouts3.csproj as the startup project should work. Let me know if any issues arise

**Comment by FireCubeStudios** [comment]
fixed
